name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: |
        cd backend
        npm install

    - name: Build Docker Image
      run: |
        docker build -t ecg-backend ./backend

    - name: Clean Up (Optional)
      run: |
        docker ps -q --filter "ancestor=ecg-backend" | xargs -r docker stop
